 
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';  

export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
// export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';

export const GET_POST_PAGE_SUCCESS = "GET_POST_PAGE_SUCCESS";

// export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

//Loading
export const LOADING = "LOADING";
// export const BOOKING_SUCCESS = "BOOKING_SUCCESS";

//Listing
export const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';  
export const GET_LISTING_CATEGORIES_SUCCESS = 'GET_LISTING_CATEGORIES_SUCCESS'; 
export const GET_LISTING_ITEM_SUCCESS = 'GET_LISTING_ITEM_SUCCESS' ;
export const GET_LISTING_WITH_CAT_SUCCESS = "GET_LISTING_WITH_CAT_SUCCESS";
export const SEARCH_LISTING_SUCCESS = "SEARCH_LISTING_SUCCESS";
export const PUSH_COMMENT_LISTING_SUCCESS = "PUSH_COMMENT_LISTING_SUCCESS";
export const SET_LISTING_ACTIVED_SUCCESS = "SET_LISTING_ACTIVED_SUCCESS"
//Page
export const GET_PAGE_MOBILE_APP_SUCCESS = "GET_PAGE_MOBILE_APP_SUCCESS";
export const GET_SETTING_SUCCESS = "GET_SETTING_SUCCESS";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_LISTING_TAGS_SUCCESS = "GET_LISTING_TAGS_SUCCESS";

//User
export const PROCESS_LISTING_CHECKOUT_SUCCESS = "PROCESS_LISTING_CHECKOUT_SUCCESS"
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS"
export const UPDATE_USER_SUCCESS  = "UPDATE_USER_SUCCESS";
export const USER_SUCCESS = "USER_SUCCESS";
export const DELETE_BOOKMARK_SUCCESS  = "DELETE_BOOKMARK_SUCCESS";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const GET_LBOOKING_SUCCESS    = 'GET_IBOOKING_SUCCESS';
export const CANCEL_LBOOKING_SUCCESS = "CANCEL_LBOOKING_SUCCESS";
export const GET_USER_SUCCESS   =   'GET_USER_SUCCESS';
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

//Search
export const SET_TAG_FROM_SEARCH = "SET_TAG_FROM_SEARCH";
export const SET_CAT_FROM_SEARCH = "SET_CAT_FROM_SEARCH";
export const SET_PRICE_RANGE_FROM_SEARCH = "SET_PRICE_RANGE_FROM_SEARCH";
export const SET_ORDER_BY_FROM_SEARCH = "SET_ORDER_BY_FROM_SEARCH";
export const SET_SORT_BY_FROM_SEARCH = "SET_SORT_BY_FROM_SEARCH";


export const GET_LISTING_LOCATIONS_SUCCESS = "GET_LISTING_LOCATIONS_SUCCESS";

//Chats
export const LAUTHOR_MESSAGE_CHAT = "LAUTHOR_MESSAGE_CHAT";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const CHAT_REPLY_SUCCESS = "CHAT_REPLY_SUCCESS";
export const GET_CHAT_REPLIES_SUCCESS = "GET_CHAT_REPLIES_SUCCESS";
export const GET_REPLIES_SUCCESS = "GET_REPLIES_SUCCESS";
export const UPDATE_FIRST_LAST_ID_SUCCESS = "UPDATE_FIRST_LAST_ID_SUCCESS";
export const CHANGE_CONTACT_SUCCESS = "CHANGE_CONTACT_SUCCESS";
export const GET_MORE_TOP_REPLIES_SUCCESS = "GET_MORE_TOP_REPLIES_SUCCESS";




